### ISSUE TITLE
Нет некоторых файлов в архиве SDK 2.0

### ISSUE THREAD

**Issue by smtu** [gokalkan/gokalkan#18]
<img width="587" alt="Screen Shot 2022-09-14 at 20 13 39" src="https://user-images.githubusercontent.com/19384761/190179154-6455a14a-49f5-444b-b80f-72c3e4ae1ae0.png">
^ нет больше такой папки в архиве SDK 2.0

теперь это выглядит вот так:
<img width="359" alt="Screen Shot 2022-09-14 at 20 17 45" src="https://user-images.githubusercontent.com/19384761/190179693-9f28dcec-6ff5-46fa-856b-7b79c3762ae0.png">

где брать недостающие файлы?
Спасибо!

**Comment by atlekbai** [comment]
Привет, @smtu !
Структура SDK, поменялась в версии 2.0. Скоро обновим инструкции и код
