### ISSUE TITLE
Repository not found

### ISSUE THREAD

**Issue by swifft17** [gokalkan/gokalkan#20]
Здравствуйте. Спасибо за Вашу работу. 
**go get github.com/doodocs/doodocs/pkg/gokalkan**
go: module github.com/doodocs/doodocs/pkg/gokalkan: git ls-remote -q origin in /home/xxx/go/pkg/mod/cache/vcs/4ac6913556d9b56dd76dc4bd42a8b622278572643852fa361f516f5ea38c76da: exit status 128:
        remote: Repository not found.
        fatal: repository 'https://github.com/doodocs/doodocs/' not found

**Comment by atlekbai** [comment]
Спасибо большое! Исправил
