### ISSUE TITLE
Двусторонний подпись

### ISSUE THREAD

**Issue by abzalafr** [gokalkan/gokalkan#24]
Добрый день!

Подскажите, пожалуйста, какой метод нужно использовать для подписания уже подписанный файл (base64). 
Получается мне нужно добавить свой подпись на подписанный документ.

Спасибо большое!

**Comment by atlekbai** [comment]
Здравствуйте! Вам нужно использовать метод [Sign](https://github.com/gokalkan/gokalkan/blob/501d58496aef5758183139bb00f7572cd8c7b05f/sign.go#L12) для многостороннего подписывания.
После подписания возвращается подпись, которую можно приложить к файлу для подтверждения.

**Comment by abzalafr** [comment]
> Здравствуйте! Вам нужно использовать метод [Sign](https://github.com/gokalkan/gokalkan/blob/501d58496aef5758183139bb00f7572cd8c7b05f/sign.go#L12) для многостороннего подписывания. После подписания возвращается подпись, которую можно приложить к файлу для подтверждения.

Спасибо большое!
