### ISSUE TITLE
Ошибка шифрования: ERROR 0x8f00019: Verify Data - encode error.

### ISSUE THREAD

**Issue by swifft17** [gokalkan/gokalkan#27]
Здравствуйте.

Беру файл, например, ОписаниеKalkanCrypt.docx из SDK, подписываю его на ezsigner.kz, затем 
	content, err := ioutil.ReadFile("ОписаниеKalkanCrypt.docx.cms")
	if err != nil {
		fmt.Println("Ошибка при чтении файла:", err)
		return
	}
и проверяю
	signature := base64.StdEncoding.EncodeToString(content)
 	flags := ckalkan.FlagSignCMS | ckalkan.FlagInBase64 | ckalkan.FlagOutBase64
	 _, err := cli.kc.VerifyData(signature, "", "", flags)
	 fmt.Println(err)

Получается ERROR 0x8f00019: Verify Data - encode error. (на на ezsigner.kz все ОК, конечно)

А с маленькими файлами (килобайт на 10) все нормально.

Не подскажете, что может быть?

**Comment by forChin** [comment]
Если подписывать не через ezsigner, а с помощью этой же библиотеке, ошибка все равно происходит. Не знаю в чем проблема, Как мне видится, вместо того, чтобы ждать ответа от авторов, можно подписывать не сам документ, а его хэш, и хранить их рядом. Как здесь описано: https://forum.pki.gov.kz/t/podpis-po-eczp/93

**Comment by swifft17** [comment]
Спасибо, что повторили проблему. Я склоняюсь к тому, что это проблема Калкана, просто как-то не верилось, что может быть такой детский глюк...

**Comment by atlekbai** [comment]
Здравствуйте! Проверил на маленьком файле и на большом. Действительно наблюдается ошибка с большими файлами при проверке подписи.

@swifft17 ваш код похож на реализацию функции [Verify](https://github.com/gokalkan/gokalkan/blob/611108d1b0835c7d10e28ea90e5f36d770898779/verify.go#L10). Тут ломается на `VerifyData`.

Однако, я попробовал проверить подпись через [VeriftDetached](https://github.com/gokalkan/gokalkan/blob/611108d1b0835c7d10e28ea90e5f36d770898779/verify.go#LL28C3-L28C3) и он работает корректно. Попробуйте использовать его. В аргемент `data` вам нужно будет передать оригинальный файл.ю

**Comment by swifft17** [comment]
Здравствуйте. К сожалению, у меня CMS со вложенными данными, оригинального файла может не быть...

**Comment by atlekbai** [comment]
Есть либа для работы с CMS. Используйте метод [DataEContent](https://github.com/github/smimesign/blob/3564e86011859c28b315328027abebb954b6bf6f/ietf-cms/protocol/protocol.go#LL194C1-L194C1).

**Comment by swifft17** [comment]
Спасибо большое за вариант.
