### ISSUE TITLE
Implementation under FreeBSD

### ISSUE THREAD

**Issue by timsan7sk** [gokalkan/gokalkan#31]
Саламалейкум, джыгиттер!
Проделанная вами работа по настоящему впечатляет.
Я пытаюсь воспользоваться написанной вами оберткой под FreeBSD и наткнулся на грабли(под Ubuntu 22 все пашет изумительно).

#### Собрал библиотеку libkalkancryptwr-64.so под FreeBSD
`objdump -x /usr/lib/libkalkancryptwr-64.so.2 | less`
![image](https://github.com/gokalkan/gokalkan/assets/86413941/e9065015-2d22-43bf-80a0-94b70898e1b8)
![image](https://github.com/gokalkan/gokalkan/assets/86413941/baa17cfe-8318-434d-91d7-e9eb7a629c47)

`ldconfig -r | grep kalkan`
`91:-lkalkancryptwr-64.2 => /usr/lib/libkalkancryptwr-64.so.2`

С вашего позволения добавил буквально пару строк в файл `kalkan.go`
![image](https://github.com/gokalkan/gokalkan/assets/86413941/e9238e86-cafb-4ce8-a8df-fc35b2aee275)

При попытке выполнения кода из `README.md` возвращает ошибку:
`2024/02/08 12:38:12 load key store error[8f00101] Библиотека не инициализирована`

Однако если сменить имя библиотеки на заведомо не верное, возвращает ошибку:
`2024/02/08 15:37:16 new kalkan client create errorlib handler error: Shared object "libkalkancryptwr-64.so" not found, required by "main"`
Значит библиотеку находит, осталось выяснить почему не инициализирует.
Попытаюсь раскопать в чем причины, о всех результатах отпишусь. Если у кого-то появится интерес, милости прошу принять участие в раскопках.

P. S.
Так же возвращается варнинг при сборке кода из `README.md`:
`get_cert_list.go:9:2: warning: non-void function does not return a value [-Wreturn-type]`
просит `return`
![image](https://github.com/gokalkan/gokalkan/assets/86413941/2d6657c1-1e48-47fa-a777-9f4485a96812)

Всем удачи,
Саламалейкум

**Comment by timsan7sk** [comment]
Ассаламуалейкум уа рахматуллахи уа баракаатуху.
Все оказалось вполне прозаично.
Добавльте пожалуйста в KalkanCrypt.h строку:
`unsigned long(*SignDataArchive)(char *alias, int flags, char *inData, int inDataLength, unsigned char *
inSign, int inSignLen, char *validPath, unsigned char *outSign, int *outSignLength);`
между `unsigned long(*SignData)...` и ` unsigned long(*SignXML)...` или замените на файл который прикреплен к мессаге и все будет в ёлочку. Если кому-то нужна либа собранная под FreeBSD до того, как её добавили в SDK, пожалуйста обращайтесь.
Еще раз выражаю огромную признательность за проделанную Вами работу!
Саламалейкум!
[KalkanCrypt.h.tar.gz](https://github.com/gokalkan/gokalkan/files/14278007/KalkanCrypt.h.tar.gz)

**Comment by Qjawko** [comment]
@timsan7sk Салам, го пулл реквест сделаешь, а мы посмотрим и заодно добавим в основную ветку чтобы работало и на Linux, и на FreeBSD

**Comment by timsan7sk** [comment]
@Qjawko Салам. Уже все сделано.
